# Generated by Django 4.2.1 on 2023-05-23 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_plain_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
